var ometajs_ = require("ometajs");var AbstractGrammar = ometajs_.grammars.AbstractGrammar;var BSJSParser = ometajs_.grammars.BSJSParser;var BSJSIdentity = ometajs_.grammars.BSJSIdentity;var BSJSTranslator = ometajs_.grammars.BSJSTranslator;//----------------------------------------------------------------------
//
// This source file is part of the furipota project.
//
// Licensed under MIT. See LICENCE for full licence information.
// See CONTRIBUTORS for the list of contributors to the project.
//
//----------------------------------------------------------------------

const ast = require("./ast");

var reserved = [
  "define",
  "import", "core", "plugin", "export", "as",
  "true", "false",
  "let", "in",
  "if", "then", "else",
  "and", "or", "not",
  "default"
];

function isValid(id) {
  return reserved.indexOf(id) === -1;
}

function makeLambda(args, expr) {
  const lastArg = args[args.length - 2];
  const recordArg = args[args.length - 1];
  return args.slice(0, -2).reduceRight(function(fn, arg) {
    return ast.Lambda(arg, ast.Identifier("_"), fn);
  }, ast.Lambda(lastArg, recordArg, expr));
}
var FuripotaParser = function FuripotaParser(source, opts) {AbstractGrammar.call(this, source, opts)};FuripotaParser.grammarName = "FuripotaParser";FuripotaParser.match = AbstractGrammar.match;FuripotaParser.matchAll = AbstractGrammar.matchAll;exports.FuripotaParser = FuripotaParser;require("util").inherits(FuripotaParser, AbstractGrammar);FuripotaParser.prototype["space"] = function $space() {return (this._seq(/^(\s)/))};
FuripotaParser.prototype["ignored"] = function $ignored() {return (this._atomic(function() {return this._rule("space",false,[],null,this["space"])}) || this._atomic(function() {return this._rule("comment",false,[],null,this["comment"])}))};
FuripotaParser.prototype["comment"] = function $comment() {var a;return (this._rule("fromTo",false,["#","\n"],null,this["fromTo"]) && ((a = this._getIntermediate()), true) && this._exec(a.slice(1)))};
FuripotaParser.prototype["ws"] = function $ws() {return (this._any(function() {  return this._atomic(function() { return this._rule("ignored",false,[],null,this["ignored"])  });}))};
FuripotaParser.prototype["sws"] = function $sws() {return (this._many(function() {  return this._atomic(function() { return this._rule("ignored",false,[],null,this["ignored"])  });}))};
FuripotaParser.prototype["kw"] = function $kw() {var xs;return this._skip() && ((xs = this._getIntermediate()), true) && (this._rule("seq",false,[xs],null,this["seq"]) && !this._atomic(function() {return (this._atomic(function() {return this._rule("letter",false,[],null,this["letter"])}) || this._atomic(function() {return this._rule("digit",false,[],null,this["digit"])}) || this._match("-") || this._match("_") || this._match(":"))}, true))};
FuripotaParser.prototype["idStart"] = function $idStart() {return (this._rule("letter",false,[],null,this["letter"]))};
FuripotaParser.prototype["idRest"] = function $idRest() {return ((this._atomic(function() {return this._rule("letter",false,[],null,this["letter"])}) || this._atomic(function() {return this._rule("digit",false,[],null,this["digit"])}) || this._match("-") || this._match("_")))};
FuripotaParser.prototype["eof"] = function $eof() {return (!this._atomic(function() {return this._rule("char",false,[],null,this["char"])}, true))};
FuripotaParser.prototype["octDigits"] = function $octDigits() {var a;return (this._seq(/^([0-7][0-7_]*)/) && ((a = this._getIntermediate()), true) && this._exec(a.replace(/_/g,"")))};
FuripotaParser.prototype["hexDigits"] = function $hexDigits() {var a;return (this._seq(/^([0-9a-fA-F][0-9a-fA-F_]*)/) && ((a = this._getIntermediate()), true) && this._exec(a.replace(/_/g,"")))};
FuripotaParser.prototype["binDigits"] = function $binDigits() {var a;return (this._seq(/^([01][01_]*)/) && ((a = this._getIntermediate()), true) && this._exec(a.replace(/_/g,"")))};
FuripotaParser.prototype["digits"] = function $digits() {var a;return (this._seq(/^([0-9][0-9_]*)/) && ((a = this._getIntermediate()), true) && this._exec(a.replace(/_/g,"")))};
FuripotaParser.prototype["exponent"] = function $exponent() {var s, d;return ((this._match("e") || this._match("E")) && this._optional(function() {return this._rule("sign",false,[],null,this["sign"])}) && ((s = this._getIntermediate()), true) && this._rule("digits",false,[],null,this["digits"]) && ((d = this._getIntermediate()), true) && this._exec(s+d))};
FuripotaParser.prototype["sign"] = function $sign() {return (this._match("+") || this._match("-"))};
FuripotaParser.prototype["stringEscape"] = function $stringEscape() {return (this._match("\\") && (this._atomic(function() {return this._match("b") && this._exec("\b")}) || this._atomic(function() {return this._match("f") && this._exec("\f")}) || this._atomic(function() {return this._match("n") && this._exec("\n")}) || this._atomic(function() {return this._match("r") && this._exec("\r")}) || this._atomic(function() {return this._match("t") && this._exec("	")}) || this._atomic(function() {return this._rule("char",false,[],null,this["char"])})))};
FuripotaParser.prototype["stringChar"] = function $stringChar() {return (this._atomic(function() {return this._rule("stringEscape",false,[],null,this["stringEscape"])}) || this._atomic(function() {var a;return (this._atomic(function() {return !this._atomic(function() {return this._rule("seq",false,['"'],null,this["seq"])}, true) && this._rule("char",false,[],null,this["char"])})) && ((a = this._getIntermediate()), true) && this._exec(a)}))};
FuripotaParser.prototype["unescapableChars"] = function $unescapableChars() {return (!this._atomic(function() {return this._rule("seq",false,['"""'],null,this["seq"])}, true) && this._rule("char",false,[],null,this["char"]))};
FuripotaParser.prototype["Identifier"] = function $Identifier() {var a;return (this._list(function() {return this._rule("idStart",false,[],null,this["idStart"]) && this._any(function() {  return this._atomic(function() { return this._rule("idRest",false,[],null,this["idRest"])  });})}, true) && ((a = this._getIntermediate()), true) && (isValid(a)) && this._exec(ast.Identifier(a)))};
FuripotaParser.prototype["Keyword"] = function $Keyword() {var a;return (this._list(function() {return this._rule("idStart",false,[],null,this["idStart"]) && this._any(function() {  return this._atomic(function() { return this._rule("idRest",false,[],null,this["idRest"])  });})}, true) && ((a = this._getIntermediate()), true) && this._match(":") && this._exec(ast.Keyword(a)))};
FuripotaParser.prototype["symbol"] = function $symbol() {return (this._list(function() {return this._many(function() {  return this._atomic(function() { return (this._atomic(function() {return this._rule("letter",false,[],null,this["letter"])}) || this._atomic(function() {return this._rule("digit",false,[],null,this["digit"])}) || this._atomic(function() {return this._rule("infix",false,[],null,this["infix"])}))  });})}, true))};
FuripotaParser.prototype["infix"] = function $infix() {var a;return ((this._atomic(function() {return this._rule("seq",false,["==="],null,this["seq"])}) || this._atomic(function() {return this._rule("seq",false,["=/="],null,this["seq"])}) || this._match(">") || this._atomic(function() {return this._rule("seq",false,[">="],null,this["seq"])}) || this._atomic(function() {return this._rule("seq",false,["<="],null,this["seq"])}) || this._match("+") || this._match("-") || this._match("*") || this._match("/")) && ((a = this._getIntermediate()), true) && this._exec(ast.Identifier(a)))};
FuripotaParser.prototype["value"] = function $value() {return (this._atomic(function() {return this._rule("Boolean",false,[],null,this["Boolean"])}) || this._atomic(function() {return this._rule("Number",false,[],null,this["Number"])}) || this._atomic(function() {return this._rule("Text",false,[],null,this["Text"])}) || this._atomic(function() {return this._rule("Vector",false,[],null,this["Vector"])}) || this._atomic(function() {return this._rule("Record",false,[],null,this["Record"])}) || this._atomic(function() {return this._rule("Lambda",false,[],null,this["Lambda"])}) || this._atomic(function() {return this._rule("Tagged",false,[],null,this["Tagged"])}))};
FuripotaParser.prototype["Boolean"] = function $Boolean() {return (this._atomic(function() {return this._rule("kw",false,["true"],null,this["kw"]) && this._exec(ast.Boolean(true))}) || this._atomic(function() {return this._rule("kw",false,["false"],null,this["kw"]) && this._exec(ast.Boolean(false))}))};
FuripotaParser.prototype["Number"] = function $Number() {var s;return (this._optional(function() {return this._rule("sign",false,[],null,this["sign"])}) && ((s = this._getIntermediate()), true) && (this._atomic(function() {var n;return this._match("0") && this._match("b") && this._rule("binDigits",false,[],null,this["binDigits"]) && ((n = this._getIntermediate()), true) && this._exec(ast.Integer(s||"+",parseInt(n,2).toString()))}) || this._atomic(function() {var n;return this._match("0") && this._match("o") && this._rule("octDigits",false,[],null,this["octDigits"]) && ((n = this._getIntermediate()), true) && this._exec(ast.Integer(s||"+",parseInt(n,8).toString()))}) || this._atomic(function() {var n;return this._match("0") && this._match("x") && this._rule("hexDigits",false,[],null,this["hexDigits"]) && ((n = this._getIntermediate()), true) && this._exec(ast.Integer(s||"+",parseInt(n,16).toString()))}) || this._atomic(function() {var a, b, c;return this._rule("digits",false,[],null,this["digits"]) && ((a = this._getIntermediate()), true) && this._match(".") && this._rule("digits",false,[],null,this["digits"]) && ((b = this._getIntermediate()), true) && this._optional(function() {return this._rule("exponent",false,[],null,this["exponent"])}) && ((c = this._getIntermediate()), true) && this._exec(ast.Decimal(s||"+",a,b,c||""))}) || this._atomic(function() {var a;return this._rule("digits",false,[],null,this["digits"]) && ((a = this._getIntermediate()), true) && this._exec(ast.Integer(s||"+",a))})))};
FuripotaParser.prototype["Text"] = function $Text() {return (this._atomic(function() {var as;return this._rule("seq",false,['"""'],null,this["seq"]) && this._list(function() {return this._any(function() {  return this._atomic(function() { return this._rule("unescapableChars",false,[],null,this["unescapableChars"])  });})}, true) && ((as = this._getIntermediate()), true) && this._rule("seq",false,['"""'],null,this["seq"]) && this._exec(ast.Text(as))}) || this._atomic(function() {var as;return this._match("\"") && this._any(function() {  return this._atomic(function() { return this._rule("stringChar",false,[],null,this["stringChar"])  });}) && ((as = this._getIntermediate()), true) && this._match("\"") && this._exec(ast.Text(as.join("")))}))};
FuripotaParser.prototype["Vector"] = function $Vector() {return (this._atomic(function() {return this._match("[") && this._rule("ws",false,[],null,this["ws"]) && this._match("]") && this._exec(ast.Vector([]))}) || this._atomic(function() {var a, as;return this._match("[") && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((a = this._getIntermediate()), true) && this._any(function() {  return this._atomic(function() { return (this._rule("ws",false,[],null,this["ws"]) && this._match(",") && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]))  });}) && ((as = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("]") && this._exec(ast.Vector([a].concat(as)))}))};
FuripotaParser.prototype["Record"] = function $Record() {return (this._atomic(function() {return this._match("{") && this._rule("ws",false,[],null,this["ws"]) && this._match("}") && this._exec(ast.Record([]))}) || this._atomic(function() {var a, xs;return this._rule("recordPair",false,[],null,this["recordPair"]) && ((a = this._getIntermediate()), true) && this._any(function() {  return this._atomic(function() { return (this._rule("sws",false,[],null,this["sws"]) && this._rule("recordPair",false,[],null,this["recordPair"]))  });}) && ((xs = this._getIntermediate()), true) && this._exec(ast.Record([a].concat(xs)))}))};
FuripotaParser.prototype["recordPair"] = function $recordPair() {var k, v;return (this._rule("Keyword",false,[],null,this["Keyword"]) && ((k = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("recordExpression",false,[],null,this["recordExpression"]) && ((v = this._getIntermediate()), true) && this._exec([k,v]))};
FuripotaParser.prototype["recordExpression"] = function $recordExpression() {return (this._atomic(function() {return this._rule("memberExpression",false,[],null,this["memberExpression"])}) || this._atomic(function() {return this._rule("Vector",false,[],null,this["Vector"])}) || this._atomic(function() {return this._rule("Shell",false,[],null,this["Shell"])}))};
FuripotaParser.prototype["Lambda"] = function $Lambda() {var as, r, e;return (this._many(function() {  return this._atomic(function() { return (this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]))  });}) && ((as = this._getIntermediate()), true) && this._optional(function() {return (this._rule("ws",false,[],null,this["ws"]) && this._match("@") && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]))}) && ((r = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("seq",false,["->"],null,this["seq"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(makeLambda(as.concat([r||ast.Identifier("_")]),e)))};
FuripotaParser.prototype["Tagged"] = function $Tagged() {var i, e;return (this._match("^") && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("simpleExpression",false,[],null,this["simpleExpression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Tagged(i,e)))};
FuripotaParser.prototype["declaration"] = function $declaration() {return (this._atomic(function() {return this._rule("Define",false,[],null,this["Define"])}) || this._atomic(function() {return this._rule("Import",false,[],null,this["Import"])}) || this._atomic(function() {return this._rule("Export",false,[],null,this["Export"])}))};
FuripotaParser.prototype["Define"] = function $Define() {return (this._atomic(function() {var i, d, e;return this._rule("kw",false,["define"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("=") && this._optional(function() {return this._rule("doc",false,[],null,this["doc"])}) && ((d = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Define(i,e,d||""))}) || this._atomic(function() {var i, as, d, e;return this._rule("kw",false,["define"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("argNames",false,[],null,this["argNames"]) && ((as = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("=") && this._optional(function() {return this._rule("doc",false,[],null,this["doc"])}) && ((d = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Define(i,makeLambda(as,e),d||""))}))};
FuripotaParser.prototype[""] = function $() {return (this._atomic(function() {var l, op, r, o, d, e;return this._skip() && this._rule("kw",false,["define"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((l = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("infix",false,[],null,this["infix"]) && ((op = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((r = this._getIntermediate()), true) && this._optional(function() {return (this._rule("ws",false,[],null,this["ws"]) && this._match("@") && this._rule("Identifier",false,[],null,this["Identifier"]))}) && ((o = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("=") && this._optional(function() {return this._rule("doc",false,[],null,this["doc"])}) && ((d = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Define(op,makeLambda([l,r,o||ast.Identifier("_")],e),d||""))}) || this._atomic(function() {var l, op, r, o, v, e;return this._skip() && this._rule("kw",false,["let"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((l = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("infix",false,[],null,this["infix"]) && ((op = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((r = this._getIntermediate()), true) && this._optional(function() {return (this._rule("ws",false,[],null,this["ws"]) && this._match("@") && this._rule("Identifier",false,[],null,this["Identifier"]))}) && ((o = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("=") && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((v = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("kw",false,["in"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Let(op,makeLambda([l,r,o||ast.Identifier("_")],v),e))}))};
FuripotaParser.prototype["argNames"] = function $argNames() {var as, r;return (this._many(function() {  return this._atomic(function() { return (this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]))  });}) && ((as = this._getIntermediate()), true) && this._optional(function() {return (this._rule("ws",false,[],null,this["ws"]) && this._match("@") && this._rule("Identifier",false,[],null,this["Identifier"]))}) && ((r = this._getIntermediate()), true) && this._exec(as.concat([r||ast.Identifier("_")])))};
FuripotaParser.prototype["doc"] = function $doc() {var xs;return (this._any(function() {  return this._atomic(function() { return (this._any(function() {  return this._atomic(function() { return this._rule("space",false,[],null,this["space"])  });}) && this._rule("comment",false,[],null,this["comment"]))  });}) && ((xs = this._getIntermediate()), true) && this._exec(xs.join("")))};
FuripotaParser.prototype["Import"] = function $Import() {return (this._atomic(function() {var k, p, i;return this._rule("kw",false,["import"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._optional(function() {return this._rule("importKind",false,[],null,this["importKind"])}) && ((k = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Text",false,[],null,this["Text"]) && ((p = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("kw",false,["as"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._exec(ast.ImportAliasing(p,i,k||"furipota"))}) || this._atomic(function() {var k, p;return this._rule("kw",false,["import"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._optional(function() {return this._rule("importKind",false,[],null,this["importKind"])}) && ((k = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Text",false,[],null,this["Text"]) && ((p = this._getIntermediate()), true) && this._exec(ast.Import(p,k||"furipota"))}))};
FuripotaParser.prototype["importKind"] = function $importKind() {return (this._atomic(function() {return this._rule("kw",false,["core"],null,this["kw"])}) || this._atomic(function() {return this._rule("kw",false,["plugin"],null,this["kw"])}))};
FuripotaParser.prototype["Export"] = function $Export() {return (this._atomic(function() {var d;return this._rule("kw",false,["export"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Define",false,[],null,this["Define"]) && ((d = this._getIntermediate()), true) && this._exec(ast.Seq([d,ast.Export(d.id)]))}) || this._atomic(function() {var i, a;return this._rule("kw",false,["export"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("kw",false,["as"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((a = this._getIntermediate()), true) && this._exec(ast.ExportAliasing(i,a))}) || this._atomic(function() {var i;return this._rule("kw",false,["export"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._exec(ast.Export(i))}))};
FuripotaParser.prototype["expression"] = function $expression() {return (this._atomic(function() {return this._rule("Lambda",false,[],null,this["Lambda"])}) || this._atomic(function() {return this._rule("Record",false,[],null,this["Record"])}) || this._atomic(function() {return this._rule("Let",false,[],null,this["Let"])}) || this._atomic(function() {return this._rule("IfThenElse",false,[],null,this["IfThenElse"])}) || this._atomic(function() {return this._rule("Pipe",false,[],null,this["Pipe"])}))};
FuripotaParser.prototype["Let"] = function $Let() {return (this._atomic(function() {var i, v, e;return this._rule("kw",false,["let"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("=") && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((v = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("kw",false,["in"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Let(i,v,e))}) || this._atomic(function() {var i, as, v, e;return this._rule("kw",false,["let"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("argNames",false,[],null,this["argNames"]) && ((as = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("=") && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((v = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("kw",false,["in"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Let(i,makeLambda(as,v),e))}))};
FuripotaParser.prototype["IfThenElse"] = function $IfThenElse() {var c, t, e;return (this._rule("kw",false,["if"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((c = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("kw",false,["then"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((t = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("kw",false,["else"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.IfThenElse(c,t,e)))};
FuripotaParser.prototype["Pipe"] = function $Pipe() {return (this._atomic(function() {var a, t;return this._rule("Pipe",false,[],null,this["Pipe"]) && ((a = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("seq",false,["|>"],null,this["seq"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Logical",false,[],null,this["Logical"]) && ((t = this._getIntermediate()), true) && this._exec(ast.Pipe(a,t))}) || this._atomic(function() {return this._rule("Logical",false,[],null,this["Logical"])}))};
FuripotaParser.prototype["Logical"] = function $Logical() {return (this._atomic(function() {var a, o, b;return this._rule("Logical",false,[],null,this["Logical"]) && ((a = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && (this._atomic(function() {return this._rule("kw",false,["and"],null,this["kw"])}) || this._atomic(function() {return this._rule("kw",false,["or"],null,this["kw"])})) && ((o = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Relational",false,[],null,this["Relational"]) && ((b = this._getIntermediate()), true) && this._exec(ast.Infix(ast.Variable(ast.Identifier(o)),a,b))}) || this._atomic(function() {return this._rule("Infix",false,[],null,this["Infix"])}))};
FuripotaParser.prototype["Infix"] = function $Infix() {return (this._atomic(function() {var l, i, r;return this._rule("Infix",false,[],null,this["Infix"]) && ((l = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("`") && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Unary",false,[],null,this["Unary"]) && ((r = this._getIntermediate()), true) && this._exec(ast.Infix(ast.Variable(i),l,r))}) || this._atomic(function() {var l, i, r;return this._rule("Infix",false,[],null,this["Infix"]) && ((l = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("`") && this._rule("qualifiedIdentifier",false,[],null,this["qualifiedIdentifier"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Unary",false,[],null,this["Unary"]) && ((r = this._getIntermediate()), true) && this._exec(ast.Infix(i,l,r))}) || this._atomic(function() {return this._rule("Postfix",false,[],null,this["Postfix"])}))};
FuripotaParser.prototype["Postfix"] = function $Postfix() {return (this._atomic(function() {var e, i, r;return this._rule("Postfix",false,[],null,this["Postfix"]) && ((e = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("|") && this._rule("ws",false,[],null,this["ws"]) && this._rule("memberExpression",false,[],null,this["memberExpression"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._optional(function() {return this._rule("Record",false,[],null,this["Record"])}) && ((r = this._getIntermediate()), true) && this._exec(ast.Invoke(i,e,r||ast.Record([])))}) || this._atomic(function() {var e, i, r;return this._rule("Postfix",false,[],null,this["Postfix"]) && ((e = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("|") && this._rule("ws",false,[],null,this["ws"]) && this._rule("memberExpression",false,[],null,this["memberExpression"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("_") && this._rule("ws",false,[],null,this["ws"]) && this._optional(function() {return this._rule("Record",false,[],null,this["Record"])}) && ((r = this._getIntermediate()), true) && this._exec(ast.Partial(i,r||ast.Record([])))}) || this._atomic(function() {return this._rule("Relational",false,[],null,this["Relational"])}))};
FuripotaParser.prototype["qualifiedIdentifier"] = function $qualifiedIdentifier() {var a, i;return (this._rule("qualifiedIdentifier",false,[],null,this["qualifiedIdentifier"]) && ((a = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match(".") && this._rule("ws",false,[],null,this["ws"]) && this._rule("symbol",false,[],null,this["symbol"]) && ((i = this._getIntermediate()), true) && this._exec(ast.Get(a,ast.Identifier(i))))};
FuripotaParser.prototype["Relational"] = function $Relational() {return (this._atomic(function() {var a, o, b;return this._rule("Relational",false,[],null,this["Relational"]) && ((a = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && (this._atomic(function() {return this._rule("seq",false,["==="],null,this["seq"])}) || this._atomic(function() {return this._rule("seq",false,["=/="],null,this["seq"])}) || this._match(">") || this._atomic(function() {return this._rule("seq",false,[">="],null,this["seq"])}) || this._match("<") || this._atomic(function() {return this._rule("seq",false,["<="],null,this["seq"])})) && ((o = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Add",false,[],null,this["Add"]) && ((b = this._getIntermediate()), true) && this._exec(ast.Infix(ast.Variable(ast.Identifier(o)),b,a))}) || this._atomic(function() {return this._rule("Add",false,[],null,this["Add"])}))};
FuripotaParser.prototype["Add"] = function $Add() {return (this._atomic(function() {var a, o, b;return this._rule("Add",false,[],null,this["Add"]) && ((a = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && (this._match("+") || this._match("-")) && ((o = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Multiply",false,[],null,this["Multiply"]) && ((b = this._getIntermediate()), true) && this._exec(ast.Infix(ast.Variable(ast.Identifier(o)),b,a))}) || this._atomic(function() {return this._rule("Multiply",false,[],null,this["Multiply"])}))};
FuripotaParser.prototype["Multiply"] = function $Multiply() {return (this._atomic(function() {var a, o, b;return this._rule("Multiply",false,[],null,this["Multiply"]) && ((a = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && (this._match("*") || this._match("/")) && ((o = this._getIntermediate()), true) && this._rule("sws",false,[],null,this["sws"]) && this._rule("Unary",false,[],null,this["Unary"]) && ((b = this._getIntermediate()), true) && this._exec(ast.Infix(ast.Variable(ast.Identifier(o)),b,a))}) || this._atomic(function() {return this._rule("Unary",false,[],null,this["Unary"])}))};
FuripotaParser.prototype["Unary"] = function $Unary() {return (this._atomic(function() {var e;return this._rule("kw",false,["not"],null,this["kw"]) && this._rule("ws",false,[],null,this["ws"]) && this._rule("Invoke",false,[],null,this["Invoke"]) && ((e = this._getIntermediate()), true) && this._exec(ast.Prefix(ast.Identifier("not"),e))}) || this._atomic(function() {return this._rule("Invoke",false,[],null,this["Invoke"])}))};
FuripotaParser.prototype["Invoke"] = function $Invoke() {return (this._atomic(function() {var i, v, r;return this._rule("Invoke",false,[],null,this["Invoke"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("memberExpression",false,[],null,this["memberExpression"]) && ((v = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._optional(function() {return this._rule("Record",false,[],null,this["Record"])}) && ((r = this._getIntermediate()), true) && this._exec(ast.Invoke(i,v,r||ast.Record([])))}) || this._atomic(function() {var i, r;return this._rule("Invoke",false,[],null,this["Invoke"]) && ((i = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match("_") && this._rule("ws",false,[],null,this["ws"]) && this._optional(function() {return this._rule("Record",false,[],null,this["Record"])}) && ((r = this._getIntermediate()), true) && this._exec(ast.Partial(i,r||ast.Record([])))}) || this._atomic(function() {return this._rule("memberExpression",false,[],null,this["memberExpression"])}))};
FuripotaParser.prototype["memberExpression"] = function $memberExpression() {return (this._atomic(function() {var m, i;return this._rule("memberExpression",false,[],null,this["memberExpression"]) && ((m = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match(".") && this._rule("ws",false,[],null,this["ws"]) && this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._exec(ast.Get(m,i))}) || this._atomic(function() {return this._rule("simpleExpression",false,[],null,this["simpleExpression"])}))};
FuripotaParser.prototype["Shell"] = function $Shell() {var cmd, args, r;return (this._rule("seq",false,["$("],null,this["seq"]) && this._rule("shellBaseArg",false,[],null,this["shellBaseArg"]) && ((cmd = this._getIntermediate()), true) && this._any(function() {  return this._atomic(function() { return (this._rule("ws",false,[],null,this["ws"]) && this._rule("shellArg",false,[],null,this["shellArg"]))  });}) && ((args = this._getIntermediate()), true) && this._optional(function() {return (this._rule("ws",false,[],null,this["ws"]) && this._match("@") && this._rule("ws",false,[],null,this["ws"]) && this._rule("Record",false,[],null,this["Record"]))}) && ((r = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match(")") && this._exec(ast.Shell(cmd,args,r||ast.Record([]))))};
FuripotaParser.prototype["shellBaseArg"] = function $shellBaseArg() {return (this._atomic(function() {var s;return this._match("'") && this._rule("symbol",false,[],null,this["symbol"]) && ((s = this._getIntermediate()), true) && this._exec(ast.ShellSymbol(s))}) || this._atomic(function() {var e;return this._rule("memberExpression",false,[],null,this["memberExpression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.ShellExpression(e))}))};
FuripotaParser.prototype["shellArg"] = function $shellArg() {return (this._atomic(function() {return this._rule("shellBaseArg",false,[],null,this["shellBaseArg"])}) || this._atomic(function() {var e;return this._rule("seq",false,["..."],null,this["seq"]) && this._rule("memberExpression",false,[],null,this["memberExpression"]) && ((e = this._getIntermediate()), true) && this._exec(ast.ShellSpread(e))}))};
FuripotaParser.prototype["simpleExpression"] = function $simpleExpression() {return (this._atomic(function() {return this._rule("Boolean",false,[],null,this["Boolean"])}) || this._atomic(function() {return this._rule("Text",false,[],null,this["Text"])}) || this._atomic(function() {return this._rule("Number",false,[],null,this["Number"])}) || this._atomic(function() {return this._rule("Vector",false,[],null,this["Vector"])}) || this._atomic(function() {return this._rule("Tagged",false,[],null,this["Tagged"])}) || this._atomic(function() {return this._rule("Shell",false,[],null,this["Shell"])}) || this._atomic(function() {var i;return this._rule("Identifier",false,[],null,this["Identifier"]) && ((i = this._getIntermediate()), true) && this._exec(ast.Variable(i))}) || this._atomic(function() {var a;return this._match("(") && this._rule("ws",false,[],null,this["ws"]) && this._rule("expression",false,[],null,this["expression"]) && ((a = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._match(")") && this._exec(a)}))};
FuripotaParser.prototype["Program"] = function $Program() {var xs;return (this._rule("ws",false,[],null,this["ws"]) && this._rule("seq",false,["%furipota/1"],null,this["seq"]) && this._any(function() {  return this._atomic(function() { return (this._rule("ws",false,[],null,this["ws"]) && this._rule("declaration",false,[],null,this["declaration"]))  });}) && ((xs = this._getIntermediate()), true) && this._rule("ws",false,[],null,this["ws"]) && this._rule("eof",false,[],null,this["eof"]) && this._exec(ast.Program(xs)))};
